#!/usr/bin/env bash
#
# Install my Rockbox scripts.
#

install_dir="$HOME/bin"
from_relative_dir="proj/coding/programs/rockbox-scripts"

for script in *; do
    case "$script" in
        "${0##*/}") continue ;;
        "LICENSE") continue ;;
        "README.md") continue ;;
    esac

    #rm -v "$install_dir/$script"
    ln -vs "../$from_relative_dir/$script" "$install_dir"
done
