#!/usr/bin/env bash
#
# Copy music to MP3 player.
#

_BASHPLATE_DIR="$HOME/.local/share/bashplate"
source "$_BASHPLATE_DIR/bashplate.sh"

mount_dir="/mnt-set/mp3-sd"

music_from="$HOME/media/music"
music_to=""

ERR_DEVICE=2

_VERBOSE=1

_usage="\
Usage: $_FILENAME [options]
Copy music to MP3 player.

  Options:
    -v, --verbose   be verbose
    -h, --help      display this help text and exit\
"

## Mount/umount functions {{{
# Try to mount device.
mount_device() {
    _log "trying to mount ${mount_dir}..."
    mount "$mount_dir"

    # tell how it went
    if [[ $? == 0 ]]; then
        _log "mounted succesfully"
    else
        _err "could not mount directory ${mount_dir}: is the device plugged in?" $ERR_DEVICE
    fi
}

# Try to unmount device.
umount_device() {
    umount "$mount_dir"

    # tell how it went
    if [[ $? == 0 ]]; then
        _log "unmounted successfully"
    else
        _err "could not unmount directory $mount_dir" $ERR_DEVICE
    fi
}
## }}}

while getopts_long :vh opt \
    verbose 0 \
    help 0 \
    "" "$@"
do
    case "$opt" in
        v|verbose) _VERBOSE=$(($_VERBOSE+1)) ;;
        h|help) _print_usage 0 ;;
		:) _err "$OPTLERR" ; _print_usage 1 ;;
    esac
done
shift $((OPTLIND-1))

mount_device
rsync -av --modify-window=10 "$music_from" "$mount_dir/$music_to"
unmount_device
