#!/usr/bin/env bash
#
# Reformat playlists and copy them to my MP3 player.
#

_BASHPLATE_DIR="$HOME/.local/share/bashplate"
source "$_BASHPLATE_DIR/bashplate.sh"

mount_dir="/mnt-set/mp3-sd"

playlists_from="$HOME/.config/mpd/playlists"
playlists_to="playlists"

ERR_DEVICE=2

_VERBOSE=1

_usage="\
Usage: $_FILENAME [options]
Reformat playlists and copy them to my MP3 player.

  Options:
    -v, --verbose   be verbose
    -h, --help      display this help text and exit\
"

## Mount/umount functions {{{
# Try to mount device.
mount_device() {
    _log "trying to mount ${mount_dir}..."
    mount "$mount_dir"

    # tell how it went
    if [[ $? == 0 ]]; then
        _log "mounted succesfully"
    else
        _err "could not mount directory ${mount_dir}: is the device plugged in?" $ERR_DEVICE
    fi
}

# Try to unmount device.
umount_device() {
    umount "$mount_dir"

    # tell how it went
    if [[ $? == 0 ]]; then
        _log "unmounted successfully"
    else
        _err "could not unmount directory $mount_dir" $ERR_DEVICE
    fi
}
## }}}

# de-duplicate all playlists
playlist-dedup "$playlists_from"/*

# copy to tmp
tmp_dir="/tmp/playlists-$(date +%s)"
mkdir "$tmp_dir"
cp -r "$playlists_from"/* "$tmp_dir"

for file in "$tmp_dir"/*; do
    mv "${file}" "${file%.*}.m3u8"
done

# make playlists suitable for Rockbox
rocklist.py "$tmp_dir"/*

mount_device
rsync -av --modify-window=10 "$tmp_dir"/* "$mount/$playlists_to"
unmount_device

rm -r "$tmp_dir"
