#!/usr/bin/env bash
#
# Remove duplicate lines from a file (i.e. duplicate songs from a
# playlist).
#

tmp_dir="/tmp/playlist-dedup-$(date +%s)"

mkdir "$tmp_dir"

for file in $@
do
    tmpfile="$tmp_dir/${file##*/}"

    awk '!seen[$0]++' "$file" > "$tmpfile"
    md5_orig="$(md5sum "$file" | cut -d " " -f1)"
    md5_new="$(md5sum "$tmpfile" | cut -d " " -f1)"

    if [[ $md5_new != $md5_orig ]]; then
        # file has changed, show changes & copy
        echo "--- $file"
        diff "$tmpfile" "$file"
        echo
        cp "$tmpfile" "$file"
    else
        # no change, just remove temp. file
        rm "$tmpfile"
    fi
done

rm -r "$tmp_dir"
